### PR TITLE
change publish to sonatype

### PR DESCRIPTION
**Pull request by kailuowang**
to actually publish, two env variables are needed
"SONATYPE_USERNAME" and "SONATYPE_PASSWORD"
These can be set to a sonatype login token, which can be generated following the [steps here](https://github.com/olafurpg/sbt-ci-release#optional-create-user-tokens)

### CODE REVIEW

**Comment by kailuowang** [comment]
these tests seem to be failing prior to these changes in my other PR as well.

**Comment by avibryant** [comment]
@kailuowang those tests are sensitive to RNG. I wonder if maybe the JVM being used to run the tests in CI has changed or and its RNG is different? Or alternatively something around FP math settings?

**Comment by kailuowang** [comment]
Jvm was changed since the old gh action step is no longer supported.  I am using the official Scala action step now. Can we change the tests to expect the new values?

**Comment by avibryant** [comment]
@kailuowang ok, yes, that's a bit of a lengthy process because we have to re-run the Simulation-Based Calibration to make sure the posteriors still look ok, but I have reproduced the test failures by switching to JDK 11 on my machine so I can work on that.

**Comment by avibryant** [comment]
@kailuowang should pass after merging with https://github.com/stripe/rainier/pull/502

**Comment by kailuowang** [comment]
@avibryant I merged in your commits, the build passes, but the CLAssistant got confused.

**Pull request merged**
