### PR TITLE
Add cats and scalacheck modules

### PR DESCRIPTION
**Pull request by andyscott**
Adds a cats module and a scalacheck module with some very basic and possibly incorrect instances.

Consider this WIP/partially baked. Feedback welcomed.

### CODE REVIEW

**Comment by avi-stripe** [comment]
Nice! This looks great.

One thing that would be really nice for the scalacheck module is a `Gen[Real=>Real]`. This should be very similar to the `Gen[Real]` and in fact I think you could trivially build `Gen[Real]` on top of it. There's a couple of uses I have in mind for this:

* It helps with a `Gen[RandomVariable]` since you can plug the `Real=>Real` into `map` or build a fn for `flatMap` from it
* Given an arbitrary `fn: Real=>Real`, `v: Double`, and `x: Variable`, it's extremely valuable to be able to check the equivalence of `fn(Real(v))` and `Evaluator(Map(x->v)).toDouble(fn(x))`

**Comment by andyscott** [comment]
That should be easy to add. I can also add the test for `Evaluator(Map(x->v)).toDouble(fn(x))`.

**Comment by andyscott** [comment]
I have some separate code for testing the Evaluator. It's still a work in progress, since generating real expressions is a good bit of work.

**Comment by avi-stripe** [comment]
LGTM

**Pull request merged**
