### PR TITLE
Rectifier

### PR DESCRIPTION
**Pull request by avi-stripe**
* Adds RectifierOp
* Uses it in the implementations of comparison ops
* Uses comparison ops for min/max
* Uses max to do the logsumexp trick

### CODE REVIEW

**Comment by avi-stripe** [comment]
We also lurked in some jacobian fixes.

**Comment by mio-stripe** [comment]
Nice! LGTM modulo a CI failure.

**Comment by avi-stripe** [comment]
looks from the tests like we broke Exponential somehow?

**Comment by mikeheaton-stripe** [comment]
I'll look into jt

**Pull request merged**
