### PR TITLE
WIP: do not distribute over multiplications automatically

### PR DESCRIPTION
**Pull request by avibryant**
Again on the theme of hoisting optimizations up into higher layers: previously, if we had something like `(x+1)(x+2) + (y+1)(y+2)` we would distribute out the multiplications before doing the sum. In the case that `x=y`, this will simplify nicely, but otherwise it just makes things worse.

Now, we never do this automatically, but added a `distribute` method to `Real` so you can request it if you know it will be a good idea.

### CODE REVIEW

**Comment by avibryant** [comment]
Marking this WIP because I'm realizing that it should distribute recursively instead of just the top-level LogLine.

**Comment by andrew-stripe** [comment]
Should I hold off reviewing for now then?

**Comment by avibryant** [comment]
@andrew-stripe yes, thanks - it's going to get hairier, might as well wait until then.

**Comment by avibryant** [comment]
closing this for now, will revisit later

**Pull request closed without merging**
