### PR TITLE
Sample EvilPlot integration

### PR DESCRIPTION
**Pull request by hibikir**
Ascii, CLI plots are nice and pretty, but some might prefer some pngs: EvilPlot can do that.

Evilplot's contours don't quite use the same algorithm as your density plots, so there are some tradeoffs: I'd argue that the large majority of plots are better, while the funnel plot doesn't show a funnel at all. Therefore, adding a new chart type that is closer to the ascii chart might be advisable.

As far as the code goes, there's very little to it: There's about 3 real statements, and the rest is just sbt changes and making the samples also output the pngs, just to show that we can. I have no special love for any of it, so feel free to ask for changes, or just make changes on top.

### CODE REVIEW

**Comment by hibikir** [comment]
travis seems unable/unwilling to find evilplot, but it finds it just fine in my `sbt test` run :?

**Comment by avi-stripe** [comment]
That's weird. I don't have much travis experience. Maybe @andyscott-stripe has thoughts?

**Comment by andyscott-stripe** [comment]
Seems reasonable to me 👍.

**Comment by avi-stripe** [comment]
I'm going to close this in favor of https://github.com/stripe/rainier/pull/106 . However, I think a simpler `plotContour` API like this has (vs the full trace/acf/pairs stuff) would still be valuable, as would getting 2.11 artifacts for evilplot.

**Pull request closed without merging**
